apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-service-config
data:
  config.yaml: |
    server:
      port: 8080
      metrics_port: 9090
      read_timeout: 15s
      write_timeout: 15s
      idle_timeout: 60s
      shutdown_timeout: 30s
    
    database:
      max_connections: 25
      max_idle_connections: 5
      connection_max_lifetime: 5m
      
    cache:
      ttl: 5m
      max_size: 1000
      
    circuit_breaker:
      max_requests: 100
      interval: 10s
      timeout: 30s
      failure_threshold: 5
      
    rate_limiter:
      requests_per_second: 100
      burst: 200
      
    observability:
      metrics:
        enabled: true
        namespace: weather_service
      tracing:
        enabled: true
        sample_rate: 0.1
      logging:
        level: info
        format: json
        
    nws_api:
      base_url: https://api.weather.gov
      timeout: 10s
      retry_count: 3
      retry_wait: 1s