apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - rbac.yaml
  - redis.yaml

images:
  - name: us-central1-docker.pkg.dev/jack-henry-20250812-180300/weather-service/weather-service
    newTag: latest