#file: noinspection KubernetesUnknownResourcesInspection
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: weather-service
  labels:
    app: weather-service
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: weather-service
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_label_version]
      targetLabel: version