apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    app: weather-service
    monitoring: prometheus
spec:
  type: ClusterIP
  selector:
    app: weather-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: weather-service-nodeport
  labels:
    app: weather-service
spec:
  type: NodePort
  selector:
    app: weather-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP