apiVersion: v1
kind: Service
metadata:
  name: weather-service-lb
  labels:
    app: weather-service
spec:
  type: LoadBalancer
  selector:
    app: weather-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http